### ISSUE TITLE
MLV2 failed to start

### ISSUE THREAD

**Issue by Hermivore8151** [Davilarek/MessageLoggerV2-fixed#9] opened 2023-04-14 23:06 UTC
I have zero idea how any of this works, so here is the preview, this happened right after zerespluginlibary decided to break
![image](https://user-images.githubusercontent.com/130803964/232168568-54a88707-b0c9-4161-b733-324141bae316.png)
apparently zeres broke due to a discord update, so it might be the same cause

**Comment by Davilarek** [comment] 2023-04-15 12:18
Duplicate of #10

**Closed as not planned by Davilarek** 2023-04-15 12:18 UTC
Labels: bug, duplicate
