### ISSUE TITLE
[Bug] Wrong sizes in logs modal (?)

### ISSUE THREAD

**Issue by xaWolff** [Davilarek/MessageLoggerV2-fixed#11] opened 2023-04-18 04:51 UTC
I get it's the second thing on the to be fixed list but I'm just wondering if it will be fixed soon. Just asking out of curiosity, thank you for fixing this plugin.

**Comment by Davilarek** [comment] 2023-04-18 09:10
Make sure you have latest BD as it should be working now

**Comment by xaWolff** [comment] 2023-04-18 19:26
It's been working I just realized I didn't specify what I meant. I was talking about the space between the sides, not really a big issue.
![image](https://user-images.githubusercontent.com/122491447/232884183-086892af-b5c7-4f48-ad77-1722a6d4e7a2.png)

**Comment by Davilarek** [comment] 2023-04-18 20:03
Oh ok, I though it's duplicate of #7 because of the title

**Comment by Davilarek** [comment] 2023-04-18 20:07
Actually I'm not exactly sure I know what you mean... Do you mean that the logs window is too big? It was like that in the original ML

**Comment by xaWolff** [comment] 2023-04-18 20:32
> 

Yeah that is what I meant, sorry for the confusion. Will it be fixed in a later update?

**Comment by Davilarek** [comment] 2023-04-18 21:17
Check if [version 2.5.7](https://github.com/Davilarek/MessageLoggerV2-fixed/commit/2a2fc03) fixes your issue

**Comment by xaWolff** [comment] 2023-04-19 05:00
Yeah it fixed it thank you!

**Closed as completed** 2023-04-19 07:08 UTC
